config/routes.rb
Rails.application.routes.draw do
  resources :weedpens

  root "weedpens#index"

end

app/models/weedpen.rb
class Weedpen < ActiveRecord::Base


	geocoded_by :address

	after_validation :geocode 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/weedpens_controller.rb
class WeedpensController < ApplicationController
  before_action :set_weedpen, only: [:show, :edit, :update, :destroy]

  # GET /weedpens
  # GET /weedpens.json
  def index
    if params[:search].present?
      @weedpens = Weedpen.near(params[:search], 50, :order => :distance)
    else
      @weedpens = Weedpen.all
    end
  end
  

  

  # GET /weedpens/1
  # GET /weedpens/1.json
  def show
    @weedpen = Weedpen.find(params[:id])

    @hash = Gmaps4rails.build_markers(@weedpens) do |weedpen, marker|
      marker.lat weedpen.latitude
      marker.lng weedpen.longitude
      marker.infowindow "<a target='blank' href='https://www.google.com/maps/place/"+"#{farm.address}"+"'>Get Directions With Google Maps</a>"
      marker.json({ title: weedpen.name })
    end
  end

  # GET /weedpens/new
  def new
    @weedpen = Weedpen.new
  end

  # GET /weedpens/1/edit
  def edit
  end

  # POST /weedpens
  # POST /weedpens.json
  def create
    @weedpen = Weedpen.new(weedpen_params)

    respond_to do |format|
      if @weedpen.save
        format.html { redirect_to @weedpen, notice: 'Weedpen was successfully created.' }
        format.json { render :show, status: :created, location: @weedpen }
      else
        format.html { render :new }
        format.json { render json: @weedpen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weedpens/1
  # PATCH/PUT /weedpens/1.json
  def update
    respond_to do |format|
      if @weedpen.update(weedpen_params)
        format.html { redirect_to @weedpen, notice: 'Weedpen was successfully updated.' }
        format.json { render :show, status: :ok, location: @weedpen }
      else
        format.html { render :edit }
        format.json { render json: @weedpen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weedpens/1
  # DELETE /weedpens/1.json
  def destroy
    @weedpen.destroy
    respond_to do |format|
      format.html { redirect_to weedpens_url, notice: 'Weedpen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weedpen
      @weedpen = Weedpen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weedpen_params
      params.require(:weedpen).permit(:latitude, :longitude, :address, :description, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weedpens_helper.rb
module WeedpensHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FindWeedpen</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/weedpens/_form.html.erb
<%= form_for(@weedpen) do |f| %>
  <% if @weedpen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weedpen.errors.count, "error") %> prohibited this weedpen from being saved:</h2>

      <ul>
      <% @weedpen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weedpens/_weedpens.html.erb
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ 
	provider: { mapTypeId: google.maps.MapTypeId.HYBRID }, 
	internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(16);
});
</script>

app/views/weedpens/edit.html.erb
<h1>Editing Weedpen</h1>

<%= render 'form' %>

<%= link_to 'Show', @weedpen %> |
<%= link_to 'Back', weedpens_path %>

app/views/weedpens/index.html.erb
<%= javascript_include_tag "gmap" %>

<p id="notice"><%= notice %></p>

<h1>Listing Weedpens</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Address</th>
      <th>Description</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<%= form_tag weedpens_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>


  <tbody>
    <% @weedpens.each do |weedpen| %>
      <tr>
        <td><%= weedpen.latitude %></td>
        <td><%= weedpen.longitude %></td>
        <td><%= weedpen.address %></td>
        <td><%= weedpen.description %></td>
        <td><%= weedpen.title %></td>
        <td><%= link_to 'Show', weedpen %></td>
        <td><%= link_to 'Edit', edit_weedpen_path(weedpen) %></td>
        <td><%= link_to 'Destroy', weedpen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Weedpen', new_weedpen_path %>


<h1>Weed Pen Map</h1>
<div id="map-container">
  <div id="map">

<script type="text/javascript">

// var map;
// function initMap() {
//   map = new google.maps.Map(document.getElementById('map'), {
//     center: {lat: 37.09024, lng: -100.712891},
//     zoom: 5
//   });
// }

// //   // var marker = new google.maps.Marker({
// //   //   position: {lat: 41.1810055, lng: -74.3380419},
// //   //   map: map,
// //   //   title: 'Weed Pens!'
// //   // });

// //  // var image = '/images/weed.jpg';
// //  //  var weedMarker = new google.maps.Marker({
// //  //    position: {lat: 41.1810055, lng: -74.3380419},
// //  //    map: map,
// //  //    icon: image
// //  //  });

// var marker;
// function createMarker(coords, map, title){
//   marker = new google.maps.Marker({
//     position: coords,
//     map: map,
//     title: title
//   });
// }



    </script>
    <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCtKF6XQLqE5lc0w0Qt_jlUzull0JFG1go&callback=initMap">
    </script>

  </div>


</div>

app/views/weedpens/new.html.erb
<h1>New Weedpen</h1>

<%= render 'form' %>

<%= link_to 'Back', weedpens_path %>

app/views/weedpens/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'weedpens' %>

<p>
  <strong>Latitude:</strong>
  <%= @weedpen.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @weedpen.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @weedpen.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @weedpen.description %>
</p>

<p>
  <strong>Title:</strong>
  <%= @weedpen.title %>
</p>

<%= link_to 'Edit', edit_weedpen_path(@weedpen) %> |
<%= link_to 'Back', weedpens_path %>


<h3>Nearby Weed Pens</h3>
<ul>
<% for weedpen in @weedpen.nearbys(30) %>
  <li><%= link_to weedpen.address, weedpen %> (<%= weedpen.distance.round(2) %> miles)</li>
<% end %>
</ul>